steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true','-P','dataflow-runner']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: 'build-dataflow-template'
    entrypoint: gcloud
    args: [ 'dataflow', 'flex-template', 'build', '$_TEMPLATE_PATH', 'image-gcr-path', '$_TEMPLATE_IMAGE', '--sdk-language', 'JAVA', '--flex-template-base-image', 'JAVA8', '--metadata-file', 'spec/metadata.json', '--jar', '/workspace/target/word-count-beam-bundled-0.1.jar', '--env', 'FLEX_TEMPLATE_JAVA_MAIN_CLASS="org.apache.beam.examples.StreamingWordCount"' ]
logsBucket: 'gs://sandbox-307310_cloudbuild_logs'